---
title: 'Introduction to the Linux command line, part 2'
subtitle: ''
author: "Updated from David Sims, Charlie George, Kevin Rue Albrecht (CCB Doks)"
institute: "Oxford Biomedical Data Science Training Programme"
date: "2023-09-12 (updated: `r Sys.Date()`)"
execute: 
  echo: false
date-format: long
format:
  revealjs: 
    code-overflow: wrap
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: img/ox_brand1_pos.gif
    css: styles.css
    fontsize: 1.5em
    footer: Updated from David Sims, Charlie George, Kevin Rue Albrecht (CCB Doks) -- Introduction to the Linux command line, part 2
# run the following line after knitting to convert HTML to PDF
# renderthis::to_pdf("./linux_more_topics/index.cluster.html", to="./linux_more_topics/04-06_Linux_Day2.pdf")
# renderthis::to_pdf("./linux_more_topics/index.cluster.html", to="./linux_more_topics/04-06_Linux_Day2_solutions.pdf")
# ^If throwing error, set: 
#options(pagedown.remote.maxattempts=40) # number of attempt in total
#options(pagedown.remote.sleeptime=2) # time in second between attempt
---

```{r}
#| label: setup
#| include: false
stopifnot(requireNamespace("htmltools"))
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
options(width = 120)
```

```{r}
#| label: load_refs
#| include: false
#| cache: false
options(htmltools.dir.version = FALSE)
library(RefManageR)
BibOptions( 
  check.entries = FALSE,
  bib.style = "authoryear",
  cite.style = "authoryear",
  max.names = 2,
  no.print.fields = c("issn", "url", "abstract", "number", "urldate", "month", "pages", "file", "note"),
  style = "markdown",
  hyperlink = "to.doc",
  dashed = TRUE)
bib <- ReadBib("bibliography.bib")
#NoCite(bib, "R")
```


```{r, eval=TRUE}
#| child: goals_and_objectives.qmd
```

## Prerequisites

- An account on the teaching cluster
- VPN to remotely connect to the University network
- Git Bash for Microsoft Windows users
 
```{r, eval=TRUE}
#| child: etc_04_processes.qmd
```

```{r, eval=TRUE}
#| child: etc_05_shell_config.qmd
```

```{r, eval=TRUE}
#| child: etc_06_data_management.qmd
```

```{r, eval=TRUE}
#| child: solution.qmd
```
