## Learning goals

<!--
High-level "big picture" objectives of the learning process.
This should be no more than 3 bullet points.
-->

<!--
## Lesson goals and objectives
<!--
This lesson is essentially the skeleton of the linux course.
We will present the genomics workflow done usually on linux and the subsequent 
days would be about learning and doing each step of the workflow while learning 
skills needed for that (e.g. version control, working on cluster using conda 
environments).
So the main goal in this lesson is to give them a shallow but comprehensive 
picture of the linux course. We can talk about this while presenting the 
learning goals and objectives below, highlighting at which point they are and 
then just present detail objectives or outline per talk.
Take care not to make this part very long, overwhelming them on the 1st day!
-->

- Understand the use of Linux for genomics (Day 1)
- Learn to work with the Linux command line (Day 1-3)
- Process genomics data in Linux (Day 4-5)

## Learning objectives

<!--
More concrete and measurable outputs.
This can range from 3 to 8 bullet points.
-->

:::: {.columns}

::: {.column width="47%"}
- <span style="color:green;">**Day 1**</span>
  + Familiarise with the genomics workflow often done on the Linux command line
  + Use basic commands and work with files in Linux
- Day 2
  + Learn how to manage processes and system resources in Linux 
  + Learn how to organise data
:::

::: {.column width="5%"}
:::

::: {.column width="47%"}
- Day 3
  + Use git and GitHub for version control 
  + Install and load bioinformatics software using Conda 
- Day 4
  + Perform RNA-seq workflow in Linux part 1
  + Submit jobs to a High Performance Computing cluster using Slurm
- Day 5
  + Perform RNA-seq workflow in Linux part 2
:::

::::

## Time outline

<!--
COPIED FROM README.md

Breakdown of time segments for lecture and exercises addressing the objectives listed above.
These are example times; adapt time, and insert/remove rows as needed.
Requirements:
- The day starts at 9:30
- There is a 10+ min break in the morning
- There is a 1+ h lunch break
- There is a 10+ min break in the afternoon
- The day ends at 16:00
-->

| Activity                                                      |  Time |
|---------------------------------------------------------------|-------|
| Welcome, introductions, setup                                 | 09:30 |
| Talk 1 - Genomics on the Linux command line                   | 10:00 |
| Talk 2 - Introduction to the Linux command line               | 10:30 |
| **Morning Break**                                             | 11:00 |
| Talk 2 Exercise 1                                             | 11:20 |
| Talk 2 - Introduction to the Linux command line, continue     | 11:50 |
| **Lunch Break**                                               | 12:30 |
| Talk 2 Exercise 2                                             | 13:30 |
| Talk 3 - Working with files and streams in Linux              | 14:10 |
| **Afternoon Break**                                           | 14:40 |
| Talk 3 Exercise 1                                             | 15:00 |
| Talk 2 and 3 Advanced exercises                               | 15:30 |
| **Day End**                                                   | 16:00 |
