---
title: 'Introduction to the Linux command line'
subtitle: 'Genomics on the Linux command Line'
author: "Charlie George & Liezel Tamon"
institute: "Oxford Biomedical Data Science Training Programme"
date: "2024-04-29 (updated: `r Sys.Date()`)"
date-format: long
execute: 
  echo: false
format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: img/ox_brand1_pos.gif
    css: styles.css
    fontsize: 1.5em
    footer: Charlie George & Liezel Tamon -- Introduction to the Linux command line
## run the following line to render HTML
# quarto::quarto_render("index.cluster.qmd")
## run the following line to render PDF (from HTML above)
# renderthis::to_pdf("index.cluster.html", "index.cluster.pdf")
## run the following line to render the solution
# quarto::quarto_render("solution.qmd")
---

```{r}
#| label: setup
#| include: false
stopifnot(requireNamespace("htmltools"))
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
options(width = 120)
```

```{r}
#| label: load_refs
#| include: false
#| cache: false
options(htmltools.dir.version = FALSE)
library(RefManageR)
BibOptions( 
  check.entries = FALSE,
  bib.style = "authoryear",
  cite.style = "authoryear",
  max.names = 2,
  no.print.fields = c("issn", "url", "abstract", "number", "urldate", "month", "pages", "file", "note"),
  style = "markdown",
  hyperlink = "to.doc",
  dashed = TRUE)
bib <- ReadBib("bibliography.bib")
# Add entries to bibliography without explicitly citing them
# NoCite(bib, "R")
```

## Credits

- David Sims
- Charlie George
- Kevin Rue-Albrecht

<!-- ## Prerequisites -->

<!-- - An account on the teaching server or cluster -->
<!-- - VPN to remotely connect to the University network -->
<!-- - Git Bash for Microsoft Windows users -->

```{r}
#| child: goals_and_objectives.qmd
```

```{r}
#| child: etc_01_genomics.qmd
```

```{r}
#| child: etc_02_introduction.qmd
```

```{r}
#| child: etc_03_streams_and_more.qmd
```
