## Lesson goals and objectives

### Learning goals

- Describe common Bioconductor data structures for single-cell data sets.
- Understand the relationship with other single-cell software
  (e.g.
  [Seurat](https://satijalab.org/seurat/),
  [Scanpy](https://scanpy.readthedocs.io/en/stable/)).

### Learning objectives

- Write a workflow that analyses single-cell RNA-sequencing data using Bioconductor packages.
- Import single-cell data from files into the <i class="fab fa-r-project"></i> session.
- Perform basic quality control and filter cells and features.
- Normalise single-cell data and inspect the results.
- Apply clustering methods and visualise the results.
- Identify markers for each cluster and visualise their expression.

::: {.notes}
- Goal: Perform the single-cell analysis workflow you learned last week with Seurat, this time using Bioconductor packages.
- Why? Seurat and Bioconductor offer many of the same features, but each also has unique methods. Learning both helps you apply the most suitable tools for different analyses.
:::
