---
title: 'Dimensionality reduction and clustering'
subtitle: '<i class="fab fa-r-project"></i> on the CCB cluster'
author: "Kevin Rue-Albrecht"
institute: "Oxford Biomedical Data Science Training Programme"
date: "2023-06-13 (updated: `r Sys.Date()`)"
date-format: long
format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: img/ox_brand1_pos.gif
    css: styles.css
    fontsize: 1.5em
    footer: Kevin Rue-Albrecht -- Dimensionality reduction and clustering
# run the following line after knitting to convert HTML to PDF
# renderthis::to_pdf("index.cluster.html")
---

```{r}
#| label: setup
#| include: false
#| cache: false
stopifnot(requireNamespace("htmltools"))
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
stopifnot(require(tidyverse))
stopifnot(require(scRNAseq))
stopifnot(require(ComplexHeatmap))
stopifnot(require(kableExtra))
stopifnot(require(scater))
stopifnot(require(airway))
stopifnot(require(reshape2))
stopifnot(require(RColorBrewer))
stopifnot(require(Rtsne))
stopifnot(require(pvclust))
stopifnot(require(pheatmap))
stopifnot(require(cowplot))
stopifnot(require(e1071))
```

```{r}
#| label: load_refs
#| include: false
options(htmltools.dir.version = FALSE)
library(RefManageR)
BibOptions(
  check.entries = FALSE,
  bib.style = "authoryear",
  cite.style = "authoryear",
  max.names = 2,
  style = "markdown",
  hyperlink = "to.doc",
  dashed = TRUE)
bib <- ReadBib("bibliography.bib")
NoCite(bib, "tidyverse")
```

```{r}
#| child: goals_and_objectives.qmd
```

## Prerequisites

- An account on the teaching cluster.

## Set up

- Launch RStudio Server on the teaching cluster.
- Start a new RStudio project called `dimensionality_and_clustering`.
- Make a copy of the template notebook for this lesson in your RStudio project.
- Open the notebook and follow along, editing and running the code as needed.

```{r}
#| child: etc.qmd
```
