## Exercise

### Part 1

We provide you with an Excel file that contains gene expression data for the nine most highly variable genes in a pancreas cancer gene expression dataset (<https://portal.gdc.cancer.gov/projects/TCGA-PAAD>), as well as metadata for the individual samples and genes.

- Import the gene expression matrix from the Excel file into the R session as a `tibble`.
  Assign it to an object named `exprs_assay`.

- Reshape the gene expression matrix in a tidy format.
  Assign it to a new object `exprs_assay_long`.

- Draw a histogram of gene expression levels for each gene in a separate facet.

## Exercise

### Part 2

- Import the sample metadata from the Excel file into the R session as a `tibble`.
  Assign it to an object named `sample_info`.

> Metadata key:
> 
> [NIH AJCC staging system](https://www.cancer.gov/publications/dictionaries/ca> ncer-terms/def/ajcc-staging-system)
> 
> - grade: how abnormal the cancer cells and tissue look under a microscope
> - T: size of the tumor and any spread of cancer into nearby tissue
> - N: spread of cancer to nearby lymph nodes
> - M: metastasis (spread of cancer to other parts of the body)
- Convert the four columns above to the factor type.

- Combine sample information with gene expression data.
  Assign the output to `exprs_sampleinfo`.

## Exercise

### Part 3

- Identify the gene with the largest absolute difference in expression between male and female patients.

- Visualise the expression of that gene across tumour grades.
  Facet by `sex`.
  Color by `T` score.

- Draw a heat map of all nine genes.
  Remove labels as well as ticks for the x-axis.
  Remove the panel grid and background.

- Repeat the heat map, grouping samples by sex.

## Further reading

- [Introduction to Tidy Transcriptomics (2021)](https://stemangiola.github.io/bioc2021_tidytranscriptomics/articles/tidytranscriptomics.html)

## References

```{r, include=TRUE, echo=FALSE, results="asis"}
PrintBibliography(bib)
```
