---
title: 'Building a tidyverse workflow'
subtitle: '<i class="fab fa-r-project"></i> for data science and genomics'
author: "Kevin Rue-Albrecht"
institute: "Oxford Biomedical Data Science Training Programme"
date: "2025-05-14 (updated: `r Sys.Date()`)"
date-format: long
format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: img/ox_brand1_pos.gif
    css: styles.css
    fontsize: 1.5em
    footer: Kevin Rue-Albrecht -- Integrated tidyverse exercise
# run the following line after knitting to convert HTML to PDF
# renderthis::to_pdf("index.cluster.html")
---

```{r setup, include = FALSE}
#| label: setup
#| include: false
#| cache: false
stopifnot(requireNamespace("htmltools"))
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
options(width = 120)
stopifnot(require(magrittr))
```

```{r, load_refs, include=FALSE, cache=FALSE}
#| label: load_refs
#| include: false
options(htmltools.dir.version = FALSE)
library(RefManageR)
BibOptions(
  check.entries = FALSE,
  bib.style = "authoryear",
  cite.style = "authoryear",
  max.names = 2,
  style = "markdown",
  hyperlink = "to.doc",
  dashed = TRUE)
bib <- ReadBib("bibliography.bib")
NoCite(bib, "R")
```

```{r}
#| child: goals_and_objectives.qmd
```

## Credits

- Liezel Tamon
- Kevin Rue-Albrecht

<!--
Docs:
- https://quarto.org/docs/get-started/hello/rstudio.html
- https://quarto.org/docs/presentations/revealjs/
- https://github.com/quarto-dev/quarto-web/blob/main/docs/presentations/revealjs/demo/index.qmd
- https://quarto.org/docs/reference/formats/presentations/revealjs.html#slides
- https://quarto.org/docs/output-formats/html-themes.html
-->

## Prerequisites

- An account on the teaching cluster.

## Set up

- Launch RStudio Server on the teaching cluster.
- Start a new RStudio project called `tidyverse_integrated`.
- Make a copy of the template notebook for this lesson in your RStudio project.
- Open the notebook and follow along, editing and running the code as needed.

```{r}
#| child: etc.qmd
```
